### ISSUE TITLE
Icon overlays appear to be broken

### ISSUE THREAD

**Issue by lxman** [perforce/p4exp#1]
Lately I have noticed that the little overlays that it puts on the file explorer icons have turned into white squares, so I can't see the original icons at all. I tried first uninstalling/reinstalling and rebooting, and that seemed to have cleared it up for a bit, but now it's back again.
![image](https://user-images.githubusercontent.com/20031555/117974091-2ad3ef80-b2fb-11eb-9155-254a8f7bc53a.png)

**Comment by ppiorunski** [comment]
@lxman Could you please raise that as an issue through support@perforce.com.

**Comment by lxman** [comment]
It appears that the issue has gone away again, and for now has not reappeared. So I'll just close this one.
